swagger: '2.0'
info:
  title: Ellucian Elevate/Quercus Common API
  description: Ellucian Elevate/Quercus Common API
  version: 1.0.0
  contact:
    name: Dwight Egerton
    email: dwight.egerton@ellucian.com
    url: www.ellucian.com
host: quercus.campusit.net
basePath: /api
tags:
  - name: Common
    description: Common API Services/Definitions
schemes:
  - https
paths: {}
definitions:
  Element(Response):
    description: Response definition
    required:
      - status
      - message
      - url
    properties:
      status:
        description: Status code
        type: integer
        format: int32
      message:
        description: Message relating to the response
        type: string
  Element(Metadata):
    description: Metadata definition
    required:
      - createdBy
      - createdOn
      - modifiedBy
      - modifiedOn
    properties:
      createdBy:
        description: Created By
        type: string
      createdOn:
        description: Created On
        type: string
        format: datetime
      modifiedBy:
        description: Created By
        type: string
      modifiedOn:
        description: Created On
        type: string
        format: datetime
      url:
        description: Full URL path for the resource
        type: string
  Response(Failed):
    description: Failed response
    required:
      - response
    properties:
      response:
        description: Description of the response
        $ref: '#/definitions/Element(Response)'
  Response(Success):
    description: Program response
    required:
      - response
    properties:
      response:
        description: Description of the response
        $ref: '#/definitions/Element(Response)'
