swagger: '2.0'
info:
  title: Common API
  description: Common API
  version: 1.0.0
  contact:
    name: Dwight Egerton
    email: dwight.egerton@ellucian.com
    url: www.ellucian.com
host: elevate.ellucian.com
basePath: /api
tags:
  - name: Common
    description: Common API Services/Definitions
schemes:
  - https
paths: {}
definitions:
  Element(Base):
    description: Base definition
    discriminator: guid
    type: object
    required:
      - guid
      - id
    properties:
      guid:
        description: Object global unique identifier (GUID)
        type: string
        readOnly: true
        format: guid
        pattern: '^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$'
      id:
        description: Object System unique identifier
        type: string
        readOnly: true
  Element(Metadata):
    description: Metadata definition
    type: object
    required:
      - modifiedOn
      - url
    properties:
      createdBy:
        description: Created By
        type: string
        readOnly: true
      createdOn:
        description: Created On
        type: string
        readOnly: true
        format: datetime
      modifiedBy:
        description: Modified By
        type: string
        readOnly: true
      modifiedOn:
        description: Modified On
        type: string
        readOnly: true
        format: datetime
      url:
        description: Full URL path for the resource
        type: string
        readOnly: true
        pattern: "(https?:\\/\\/(?:www\\.|(?!www))[^\\s\\.]+\\.[^\\s]{2,}|www\\.[^\\s]+\\.[^\\s]{2,})"
  Element(Response):
    description: Response definition
    type: object
    required:
      - status
      - message
    properties:
      status:
        description: Status code
        type: integer
        readOnly: true
        format: int32
      message:
        description: Message relating to the response
        type: string
        readOnly: true
  Response(Failed):
    description: Failed response
    type: object
    required:
      - response
    properties:
      response:
        description: Status of the response
        $ref: '#/definitions/Element(Response)'
  Response(Success):
    description: Successful response
    type: object
    required:
      - response
    properties:
      response:
        description: Status of the response
        $ref: '#/definitions/Element(Response)'
      metadata:
        description: Metadata about the object/request
        $ref: '#/definitions/Element(Metadata)'
parameters:
  Path(id):
    name: id
    description: Object unique identifier reference
    in: path
    required: true
    type: string
  Header(auth):
    name: auth
    description: Authentication token passed in via header
    in: header
    required: false
    type: string
  Query(auth):
    name: auth
    description: Authentication token passed in via query
    in: query
    required: false
    type: string
responses:
  Success(200):
    description: Successfully process the request
    schema:
      $ref: '#/definitions/Response(Success)'
  Unauthorised(401):
    description: Unauthorised need to provided authentication before being able to perform operation
    schema:
      $ref: '#/definitions/Response(Failed)'
  Forbidden(403):
    description: Forbidden access to retrieve the requested information
    schema:
      $ref: '#/definitions/Response(Failed)'
  Error(500):
    description: System error when trying to retrieve the requested information
    schema:
      $ref: '#/definitions/Response(Failed)'
