swagger: '2.0'
info:
  title: Ellucian Elevate/Quercus Common API
  description: Ellucian Elevate/Quercus Common API
  version: 1.0.0
  contact:
    name: Dwight Egerton
    email: dwight.egerton@ellucian.com
    url: www.ellucian.com
host: quercus.campusit.net
basePath: /api
tags:
  - name: Common
    description: Common API Services/Definitions
schemes:
  - https
paths: {}
definitions:
  Element(BaseObject):
    description: Object definition
    type: object
    required:
      - metadata
      - guid
      - id
    properties:
      metadata:
        description: Base object metadata
        $ref: '#/definitions/Element(Metadata)'
      guid:
        description: Base object global unique identifier (GUID)
        type: string
        format: guid
        pattern: '^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$'
      id:
        description: Base object System unique identifier
        type: string
  Element(Metadata):
    description: Metadata definition
    type: object
    required:
      - modifiedOn
    properties:
      createdBy:
        description: Created By
        type: string
      createdOn:
        description: Created On
        type: string
        format: datetime
      modifiedBy:
        description: Modified By
        type: string
      modifiedOn:
        description: Modified On
        type: string
        format: datetime
      url:
        description: Full URL path for the resource
        type: string
  Element(Response):
    description: Response definition
    required:
      - status
      - message
      - url
    properties:
      status:
        description: Status code
        type: integer
        format: int32
      message:
        description: Message relating to the response
        type: string
  Response(Failed):
    description: Failed response
    type: object
    required:
      - response
    properties:
      response:
        description: Description of the response
        $ref: '#/definitions/Element(Response)'
  Response(Success):
    description: Program response
    type: object
    required:
      - response
    properties:
      response:
        description: Description of the response
        $ref: '#/definitions/Element(Response)'
