swagger: '2.0'
info:
  title: Ellucian Elevate/Quercus Common API
  description: Ellucian Elevate/Quercus Common API
  version: 1.0.0
  contact:
    name: Dwight Egerton
    email: dwight.egerton@ellucian.com
    url: www.ellucian.com
host: quercus.campusit.net
basePath: /api
tags:
  - name: Common
    description: Common API Services/Definitions
schemes:
  - https
paths: {}
definitions:
  Element(Base):
    description: Base definition
    type: object
    required:
      - metadata
      - guid
      - id
    properties:
      metadata:
        description: Object metadata
        $ref: '#/definitions/Element(Metadata)'
        readOnly: true
      guid:
        description: Object global unique identifier (GUID)
        type: string
        format: guid
        pattern: '^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$'
        readOnly: true
      id:
        description: Object System unique identifier
        type: string
        readOnly: true
  Element(Metadata):
    description: Metadata definition
    type: object
    required:
      - modifiedOn
    properties:
      createdBy:
        description: Created By
        type: string
        readOnly: true
      createdOn:
        description: Created On
        type: string
        format: datetime
        readOnly: true
      modifiedBy:
        description: Modified By
        type: string
        readOnly: true
      modifiedOn:
        description: Modified On
        type: string
        format: datetime
        readOnly: true
      url:
        description: Full URL path for the resource
        type: string
        pattern: '(https?:\/\/(?:www\.|(?!www))[^\s\.]+\.[^\s]{2,}|www\.[^\s]+\.[^\s]{2,})'
  Element(Response):
    description: Response definition
    type: object
    required:
      - status
      - message
    properties:
      status:
        description: Status code
        type: integer
        format: int32
      message:
        description: Message relating to the response
        type: string
  Response(Failed):
    description: Failed response
    type: object
    required:
      - response
    properties:
      response:
        description: Description of the response
        $ref: '#/definitions/Element(Response)'
  Response(Success):
    description: Program response
    type: object
    required:
      - response
    properties:
      response:
        description: Description of the response
        $ref: '#/definitions/Element(Response)'
