swagger: '2.0'
info:
  title: Program API
  description: Program API
  version: 1.0.0
  contact:
    name: Dwight Egerton
    email: dwight.egerton@ellucian.com
    url: 'http://www.ellucian.com'
host: quercus.campusit.net
basePath: /api
tags:
  - name: Programs
    description: Services/Definitions related to the management of Programs
schemes:
  - https
paths:
  /programs:
    get:
      summary: Summary available programs
      operationId: getSummary
      tags:
        - Programs
      consumes: []
      produces:
        - application/json
      parameters:
        - name: auth
          description: Authentication token passed by calling service when not using the standard security
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Successfully retrieved the programs summary
          schema:
            $ref: '#/definitions/Response(Programs)'
        '401':
          description: Unauthorised need to provided authentication before being able to retrieve the programs summary
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '403':
          description: Forbidden access to retrieve the programs summary
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '500':
          description: System error when trying to retrieve the programs summary
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
definitions:
  Element(ProgramSmry):
    description: Program definition
    allOf:
      - $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Element(Base)'
  Response(Programs):
    description: Programs response
    type: object
    required:
      - response
      - programs
    properties:
      response:
        description: Description of the response
        $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Element(Response)'
      programs:
        description: List of matching available programs
        type: array
        minLength: 0
        items:
          $ref: '#/definitions/Element(ProgramSmry)'
