swagger: '2.0'
info:
  title: Program API
  description: Program API
  version: 1.0.0
  contact:
    name: Dwight Egerton
    email: dwight.egerton@ellucian.com
    url: 'http://www.ellucian.com'
host: quercus.campusit.net
basePath: /api
tags:
  - name: Programs
    description: Services/Definitions related to the management of Programs
schemes:
  - https
paths:
  /programs:
    get:
      summary: Summary available programs
      operationId: getSummary
      tags:
        - Programs
      consumes: []
      produces:
        - application/json
      parameters:
        - name: auth
          description: Authentication token passed by calling service when not using the standard security
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Successfully retrieved the programs summary
          schema:
            $ref: '#/definitions/Response(Programs)'
        '401':
          description: Unauthorised need to provided authentication before being able to retrieve the programs summary
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '403':
          description: Forbidden access to retrieve the programs summary
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '500':
          description: System error when trying to retrieve the programs summary
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
    post:
      summary: Create new program
      operationId: createProgram
      tags:
        - Programs
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: auth
          description: Authentication token passed by calling service when not using the standard security
          in: query
          required: false
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Request(Program)'
      responses:
        '200':
          description: Successfully updated the programs queues and/or preferences
          schema:
            $ref: '#/definitions/Response(Program)'
        '401':
          description: Unauthorised need to provided authentication before being able to update the programs queues and/or preferences
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '403':
          description: Forbidden access to update the programs queues and/or preferences
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '500':
          description: System error when trying to update the programs queues and/or preferences
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
  '/programs/{id}':
    get:
      summary: Retrieve a program using the unique identifier
      operationId: getProgram
      tags:
        - Programs
      consumes: []
      produces:
        - application/json
      parameters:
        - name: id
          description: The program unique identifier
          in: path
          required: true
          type: string
        - name: auth
          description: Authentication token passed by calling service when not using the standard security
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Successfully retrieved the program
          schema:
            $ref: '#/definitions/Response(Program)'
        '401':
          description: Unauthorised need to provided authentication before being able to retrieve the program
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '403':
          description: Forbidden access to retrieve the program
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '404':
          description: Nothing found no matching program
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '500':
          description: System error when trying to retrieve the program
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
    put:
      summary: Update a program using the unique identifier
      operationId: updateProgram
      tags:
        - Programs
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          description: The program unique identifier
          in: path
          required: true
          type: string
        - name: auth
          description: Authentication token passed by calling service when not using the standard security
          in: query
          required: false
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Request(Program)'
      responses:
        '200':
          description: Successfully updated the program
          schema:
            $ref: '#/definitions/Response(Program)'
        '401':
          description: Unauthorised need to provided authentication before being able to update the program
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '403':
          description: Forbidden access to update the program
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '404':
          description: Nothing found no matching program
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '500':
          description: System error when trying to update the program
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
    delete:
      summary: Remove a program using the unique identifier
      operationId: removeProgram
      tags:
        - Programs
      consumes: []
      produces:
        - application/json
      parameters:
        - name: id
          description: The program unique identifier
          in: path
          required: true
          type: string
        - name: auth
          description: Authentication token passed by calling service when not using the standard security
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Successfully removed the program
          schema:
            $ref: '#/definitions/Response(Program)'
        '401':
          description: Unauthorised need to provided authentication before being able to remove the program
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '403':
          description: Forbidden access to remove the program
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Response(Failed)'
        '404':
          description: Nothing found no matching program
          schema:
            $ref: 'common.yaml#/definitions/Response(Failed)'
        '500':
          description: System error when trying to remove the program
          schema:
            $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Element(Metadata)'
definitions:
  Element(ProgramSmry):
    description: Program definition
    type: object
    required:
      - code
    properties:
      code:
        description: Program code
        type: string
        pattern: '^[a-zA-Z0-9]{16}$'
      description:
        description: Program description
        type: string
        maxLength: 80
      status:
        description: Status
        type: integer
        format: int32
      statusDescription:
        description: Status description
        type: string
        readOnly: true
    additionalProperties:
      description: Inherited properties from the Base object
      $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Element(Base)'
  Element(ProgramFull):
    description: Program definition
    type: object
    properties:
      approved:
        description: Date approved
        type: string
        format: datetime
      closed:
        description: Date closed
        type: string
        format: datetime
      department:
        description: Department code
        type: integer
        format: int32
      departmentDescription:
        description: Department description
        type: string
        readOnly: true
    additionalProperties:
      description: Inherited properties from the Program summary
      $ref: '#/definitions/Element(ProgramSmry)'
  Request(Program):
    description: Program request
    type: object
    required:
      - program
    properties:
      program:
        description: Description of the program
        $ref: '#/definitions/Element(ProgramFull)'
  Response(Program):
    description: Program response
    type: object
    required:
      - response
    properties:
      response:
        description: Description of the response
        $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Element(Response)'
      program:
        description: Description of the program
        $ref: '#/definitions/Element(ProgramFull)'
  Response(Programs):
    description: Programs response
    type: object
    required:
      - response
      - programs
    properties:
      response:
        description: Description of the response
        $ref: 'https://raw.githubusercontent.com/egertond/swagger/master/common.yaml#/definitions/Element(Response)'
      programs:
        description: List of matching available programs
        type: array
        minLength: 0
        items:
          $ref: '#/definitions/Element(ProgramSmry)'
